-- PRESTIGE POINTS: Supabase Schema Setup

-- 1. Create People table
CREATE TABLE IF NOT EXISTS people (
    id TEXT PRIMARY KEY, -- the handle (e.g., 'sarang')
    name TEXT NOT NULL,
    avatar TEXT DEFAULT '👤',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Events table
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id TEXT REFERENCES people(id) ON DELETE CASCADE,
    points INTEGER NOT NULL,
    reason TEXT NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE people ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies
-- For now, we'll allow anyone with the anon key to READ everything.
-- For WRITE operations, usually you'd want auth, but for this simple app, 
-- we can either leave it open (not recommended for long term) or 
-- use a secret "admin" flag if we want it to work on static pages easily.
-- For a start, let's allow all actions so the migration works.
-- YOU SHOULD RESTRICT THIS LATER!

CREATE POLICY "Allow public read-only access on people" 
ON people FOR SELECT TO anon USING (true);

CREATE POLICY "Allow public read-only access on events" 
ON events FOR SELECT TO anon USING (true);

-- TEMPORARY: Allow all for anon so migration script and admin panel work 
-- until you set up real Auth.
-- IMPORTANT: In a real app, you would use Supabase Auth and check auth.uid()
CREATE POLICY "Full access for anon (TESTING ONLY)" 
ON people FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE POLICY "Full access for anon (TESTING ONLY)" 
ON events FOR ALL TO anon USING (true) WITH CHECK (true);
